'use strict';
/**
 * P3 — canonical public-demo dataset builder: "Pearl Dental Center" (مركز
 * اللؤلؤة لطب الأسنان), a fully fictional clinic, ~6 months of coherent
 * synthetic accounting history in KWD (3 decimals).
 *
 * Used identically by (a) the one-time initial demo seed and (b) every
 * scheduled/manual demo reset (POST /api/demo/reset, server.js) — both call
 * buildDemoDatabase(), so "canonical seed" always means the exact same
 * output. ZERO real patient/vendor/employee/financial data of any kind —
 * every name/phone/email/amount below is invented for this file.
 *
 * Deterministic (no Math.random()/Date.now()) so a reset always reproduces
 * byte-identical financials — the whole point of a "canonical seed".
 */
const { DEFAULT_COA, DEFAULT_ROLES } = require('./defaults');
const bcrypt = require('bcryptjs');

// Fixed, intentionally PUBLIC demo credentials — shown directly on the
// login page's "Try Demo" button/text (Part 9). Not a secret: the whole
// point of a public demo is that anyone can log in as this restricted,
// read-mostly role. Never used for the admin account, which keeps its own
// real ADMIN_DEFAULT_PASSWORD.
const DEMO_USERNAME = 'demo';
const DEMO_PASSWORD = 'Demo@2026';
// The app has two independent branding sources that aren't kept in sync
// (GET /api/public/branding reads db.companyInfo; the post-login header
// reads config.brand.name) — both are set to the same fictional name so
// the demo doesn't show "بوبيان" (the app's own generic default) anywhere.
const DEMO_BRAND_NAME = 'مركز اللؤلؤة لطب الأسنان';

// Simple seeded PRNG (mulberry32) — deterministic, so every reset produces
// the exact same dataset (same days have revenue, same amounts, etc.).
function makeRng(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const round3 = n => Math.round((n + Number.EPSILON) * 1000) / 1000;

// Anchor date: the seed always represents "today minus ~180 days" through
// "today" at generation time, but callers pass an explicit asOf so the
// output is reproducible in tests (no bare `new Date()`).
function buildDemoDatabase(asOfISO) {
  const asOf = new Date(asOfISO);
  const rng = makeRng(20260827);
  const dayMs = 86400000;
  const dateStr = d => d.toISOString().slice(0, 10);
  const daysAgo = n => dateStr(new Date(asOf.getTime() - n * dayMs));

  const coa = DEFAULT_COA.map(a => ({ ...a }));
  const findAcc = code => coa.find(a => a.code === code);
  // 3900 (أرصدة افتتاحية) isn't in DEFAULT_COA — setVendorOpening() (server.js)
  // creates it on demand the first time it's needed. Added proactively here,
  // in the exact same shape, so a clean first boot needs zero repair-suite
  // "account-restored" action for it either.
  coa.push({ id: '3900', code: '3900', name: 'أرصدة افتتاحية', type: 'equity', parent: '3000', parentId: '3000', normalBalance: 'credit', status: 'active', balance: 0, createdAt: new Date().toISOString() });

  const journalEntries = [];
  const auditLog = [];
  let jeSeq = 0;
  const nextJeId = () => 'DEMO-JE-' + String(++jeSeq).padStart(5, '0');

  function addAudit(action, resourceType, resourceId, at) {
    auditLog.unshift({
      id: 'DEMO-AUD-' + auditLog.length, at, user: 'system',
      action, resourceType, resourceId, outcome: 'success',
    });
  }

  // Posts a balanced JE and returns it. `lines` are {code, debit, credit}.
  // sourceId (optional): mirrors the real business-logic writers
  // (buildAndPostVendorBill, buildAndPostPatientReceivable, the pay/collect
  // routes) which stamp source/sourceId on every JE they post — required so
  // downstream code (the vendor-statement hotfix's legacy-journal exclusion,
  // "go to source" deep-links) can recognize these as modern-subledger
  // entries, not raw legacy postings.
  function postJE({ id, date, desc, ref, type, source, sourceId, lines }) {
    const totalDebit = round3(lines.reduce((s, l) => s + (l.debit || 0), 0));
    const totalCredit = round3(lines.reduce((s, l) => s + (l.credit || 0), 0));
    const je = {
      id: id || nextJeId(), date, desc, description: desc, ref, reference: ref,
      type, source, sourceId: sourceId || null, totalDebit, totalCredit, autoGenerated: true,
      createdAt: date + 'T09:00:00.000Z',
      lines: lines.map(l => ({
        accountId: l.code, accountCode: l.code,
        accountName: (findAcc(l.code) || {}).name || l.code,
        debit: round3(l.debit || 0), credit: round3(l.credit || 0),
      })),
    };
    journalEntries.push(je);
    return je;
  }

  // ═══ Doctors ═══
  const doctors = [
    { id: 'doc-pearl-1', name: 'د. سارة العتيبي', specialty: 'تقويم الأسنان', target: 4000, commission: 35, lab: 40, insurance: 12 },
    { id: 'doc-pearl-2', name: 'د. يوسف الرشيدي', specialty: 'جراحة الفم', target: 3500, commission: 30, lab: 35, insurance: 10 },
    { id: 'doc-pearl-3', name: 'د. مريم الفهد', specialty: 'طب أسنان عام', target: 3000, commission: 28, lab: 30, insurance: 10 },
  ];

  // ═══ Employees (payroll) ═══
  const employees = [
    { id: 'emp-pearl-1', name: 'نورة الكندري', position: 'مديرة الاستقبال', salary: 450 },
    { id: 'emp-pearl-2', name: 'فهد العجمي', position: 'مساعد طبيب', salary: 380 },
    { id: 'emp-pearl-3', name: 'هدى المطيري', position: 'محاسبة', salary: 500 },
    { id: 'emp-pearl-4', name: 'علي الصباح', position: 'فني أشعة', salary: 420 },
  ];

  // ═══ Vendors ═══
  const vendors = [
    { id: 'vnd-pearl-1', name: 'شركة اللؤلؤة للمستلزمات الطبية', accountId: '2101', openingBalance: 620.500, openingDate: daysAgo(178) },
    { id: 'vnd-pearl-2', name: 'مختبر الخليج لتركيبات الأسنان', accountId: '2102', openingBalance: 0 },
    { id: 'vnd-pearl-3', name: 'شركة الكهرباء والماء', accountId: '2103', openingBalance: 0 },
    { id: 'vnd-pearl-4', name: 'وكالة النجمة للتسويق', accountId: '2104', openingBalance: 0 },
  ];
  vendors.forEach(v => coa.push({ id: v.accountId, code: v.accountId, name: v.name, type: 'liability', parent: '2100', balance: 0 }));

  // ═══ Insurance companies (referenced by insurance claims) ═══
  const insuranceCompanies = ['شركة الخليج للتأمين', 'شركة وربة للتأمين'];

  // ═══ Patients (fictional, with receivables) ═══
  const patientNames = [
    'أحمد الظفيري', 'فاطمة العنزي', 'خالد المري', 'العنود الشمري', 'بدر السالم',
    'شيخة الرشيد', 'ناصر القحطاني', 'ريم الدوسري', 'سلطان العون', 'دانة الحربي',
    'مشعل الخالدي', 'لولوة النصار', 'طلال البدر', 'أمل الغانم', 'راشد المزيني',
    'وداد العصفور', 'سعود الحمدان', 'جواهر السبيعي', 'فيصل الجابر', 'منال العتيبي',
  ];
  const patients = patientNames.map((name, i) => ({
    id: 'pat-pearl-' + (i + 1), name, phone: '5' + String(1000000 + i * 37).slice(-7),
    email: 'patient' + (i + 1) + '@example-demo.test',
  }));

  // ═══ Fixed assets ═══
  const fixedAssets = [
    { id: 'ast-pearl-1', code: 'FA-P-01', name: 'كرسي أسنان كهربائي', category: 'أجهزة طبية', purchaseDate: daysAgo(175), cost: 2400, usefulLife: 5, method: 'straight-line', salvageValue: 0, coaAccount: '1510', accDepAccount: '1590', depExpAccount: '5800', payMethod: 'bank', status: 'active' },
    { id: 'ast-pearl-2', code: 'FA-P-02', name: 'جهاز أشعة بانوراما', category: 'أجهزة طبية', purchaseDate: daysAgo(170), cost: 3600, usefulLife: 6, method: 'straight-line', salvageValue: 0, coaAccount: '1510', accDepAccount: '1590', depExpAccount: '5800', payMethod: 'bank', status: 'active' },
    { id: 'ast-pearl-3', code: 'FA-P-03', name: 'أجهزة حاسوب الاستقبال', category: 'معدات مكتبية', purchaseDate: daysAgo(165), cost: 540, usefulLife: 3, method: 'straight-line', salvageValue: 0, coaAccount: '1530', accDepAccount: '1590', depExpAccount: '5800', payMethod: 'cash', status: 'active' },
  ];

  // ═══ Opening balance JEs (day -180): capital/cash/bank/assets, and a
  // SEPARATE dedicated per-vendor opening entry for every vendor with an
  // openingBalance — structurally identical to what setVendorOpening()
  // itself produces (server.js), not a company-formation line item. This
  // is required, not cosmetic: runAutoRepairSuite()'s vendor-opening-
  // restored step (server.js) only recognizes a vendor's opening as
  // already posted when a journal entry with id === 'JE-VND-OPEN-'+
  // vendor.id exists (its ref-based fallback checks look for 'OPEN-'+
  // vendor.id, which setVendorOpening() itself never actually writes —
  // a pre-existing quirk in that function, not something this seed
  // changes). Folding a vendor's opening into the combined formation
  // entry left that check failing, so the repair suite correctly (by
  // its own logic) posted a SECOND opening entry on first boot. Generic
  // over every vendor — not a fix specific to any one vendor id.
  const openDate = daysAgo(180);
  const assetCost = round3(fixedAssets.reduce((s, a) => s + a.cost, 0));
  const vendorOpenings = round3(vendors.reduce((s, v) => s + (v.openingBalance || 0), 0));
  const openingCapital = 8000;
  const openingCash = 500;
  const openingBank = round3(openingCapital - openingCash - assetCost);
  postJE({
    // ref must be exactly 'OPENING' — matches what runAutoRepairSuite's
    // opening-refs-normalized step (server.js) already normalizes any
    // type:'opening' entry to; setting it directly here avoids a
    // no-op-financially but still logged "normalized" repair action on
    // a fresh boot.
    date: openDate, desc: 'رصيد افتتاحي — تأسيس مركز اللؤلؤة لطب الأسنان', ref: 'OPENING', type: 'opening', source: 'opening',
    lines: [
      { code: '1100', debit: openingCash },
      { code: '1110', debit: openingBank },
      { code: '1510', debit: round3(fixedAssets.filter(a => a.coaAccount === '1510').reduce((s, a) => s + a.cost, 0)) },
      { code: '1530', debit: round3(fixedAssets.filter(a => a.coaAccount === '1530').reduce((s, a) => s + a.cost, 0)) },
      { code: '3100', credit: openingCapital },
    ],
  });
  addAudit('auto-repair-startup', 'database', null, openDate + 'T08:00:00.000Z');

  vendors.filter(v => (v.openingBalance || 0) > 0).forEach(v => {
    postJE({
      id: 'JE-VND-OPEN-' + v.id, date: v.openingDate || openDate,
      desc: `رصيد افتتاحي — ${v.name}`, ref: 'OB-' + v.accountId, type: 'vendor-opening', source: 'vendor-opening',
      lines: [{ code: '3900', debit: v.openingBalance }, { code: v.accountId, credit: v.openingBalance }],
    });
  });

  // ═══ Daily revenue + a same-day cash expense on ~2/3 of business days ═══
  // Business days: every day except Friday (Kuwait weekend day observed here).
  const dailyData = [];
  const expenses = [];
  let expSeq = 0;
  const feeRate = 0.0065; // card network fee, matches production's own 0.65%
  for (let d = 179; d >= 1; d--) {
    const date = daysAgo(d);
    const dow = new Date(date).getUTCDay(); // 0=Sun..6=Sat; 5=Fri (weekend)
    if (dow === 5) continue;
    const base = 120 + rng() * 180; // 120-300 KWD/day base revenue
    const cash = round3(base * (0.25 + rng() * 0.15));
    const knet = round3(base * (0.30 + rng() * 0.15));
    const visa = round3(base * (0.15 + rng() * 0.10));
    const insurance = round3(rng() < 0.35 ? base * (0.15 + rng() * 0.15) : 0);
    const total = round3(cash + knet + visa + insurance);
    dailyData.push({ date, cash, knet, visa, insurance, total });

    // Card revenue is recognized GROSS (credit 4110/4120 for the full charge);
    // the network fee is a separate expense line (5750) reducing what's
    // actually received net into the receivable account (1125) — the same
    // "unified" shape already used by the real app's own card-revenue
    // postings (see runAutoRepairSuite's card-revenue-unified-to-receivable
    // step, server.js). Debits: cash + knetNet + knetFee + visaNet + visaFee
    // + insurance = cash + knet + visa + insurance = Credits: cash + knet +
    // visa + insurance. Always balances.
    const knetNet = round3(knet * (1 - feeRate));
    const knetFee = round3(knet - knetNet);
    const visaNet = round3(visa * (1 - feeRate));
    const visaFee = round3(visa - visaNet);
    const lines = [];
    if (cash > 0) lines.push({ code: '1100', debit: cash });
    if (knet > 0) { lines.push({ code: '1125', debit: knetNet }); if (knetFee > 0) lines.push({ code: '5750', debit: knetFee }); }
    if (visa > 0) { lines.push({ code: '1125', debit: visaNet }); if (visaFee > 0) lines.push({ code: '5750', debit: visaFee }); }
    if (insurance > 0) lines.push({ code: '1130', debit: insurance });
    if (cash > 0) lines.push({ code: '4100', credit: cash });
    if (knet > 0) lines.push({ code: '4110', credit: knet });
    if (visa > 0) lines.push({ code: '4120', credit: visa });
    if (insurance > 0) lines.push({ code: '4150', credit: insurance });
    postJE({ date, desc: 'إيراد يومي ' + date, ref: 'REV-' + date, type: 'daily-income', source: 'daily-income', lines });

    if (rng() < 0.12) {
      const amt = round3(3 + rng() * 15);
      const cat = rng() < 0.5 ? { code: '5900', name: 'مصاريف أخرى متنوعة' } : { code: '5740', name: 'قرطاسية ومطبوعات' };
      expenses.push({ id: 'demo-exp-' + (++expSeq), date, desc: cat.name, amount: amt, accountCode: cat.code, payMethod: 'cash' });
      postJE({ date, desc: cat.name, ref: 'EXP-' + date + '-' + expSeq, type: 'expense', source: 'expenses', lines: [{ code: cat.code, debit: amt }, { code: '1100', credit: amt }] });
    }
  }

  // ═══ Monthly recurring expenses: rent + utilities + marketing, 6 months ═══
  for (let m = 5; m >= 0; m--) {
    const date = daysAgo(m * 30 + 3);
    postJE({ date, desc: 'إيجار العيادة — شهري', ref: 'RENT-' + date, type: 'expense', source: 'recurring-expenses', lines: [{ code: '5300', debit: 350 }, { code: '1110', credit: 350 }] });
    const utilAmt = round3(45 + rng() * 20);
    postJE({ date, desc: 'مرافق — كهرباء وماء', ref: 'UTIL-' + date, type: 'expense', source: 'recurring-expenses', lines: [{ code: '5400', debit: utilAmt }, { code: '1110', credit: utilAmt }] });
    postJE({ date, desc: 'تسويق وإعلان — شهري', ref: 'MKT-' + date, type: 'expense', source: 'recurring-expenses', lines: [{ code: '5600', debit: 60 }, { code: '1110', credit: 60 }] });
  }

  // ═══ Monthly payroll, 6 months ═══
  const payroll = [];
  for (let m = 5; m >= 0; m--) {
    const date = daysAgo(m * 30 + 1);
    const totalSalary = round3(employees.reduce((s, e) => s + e.salary, 0));
    payroll.push({ id: 'demo-pay-' + m, month: date.slice(0, 7), employees: employees.map(e => ({ id: e.id, name: e.name, salary: e.salary })), total: totalSalary });
    postJE({ date, desc: 'استحقاق رواتب ' + date.slice(0, 7), ref: 'PAY-' + date.slice(0, 7), type: 'payroll', source: 'payroll', lines: [{ code: '5120', debit: totalSalary }, { code: '2200', credit: totalSalary }] });
    postJE({ date: daysAgo(m * 30 - 2 >= 0 ? m * 30 - 2 : 0), desc: 'صرف رواتب ' + date.slice(0, 7), ref: 'PAYOUT-' + date.slice(0, 7), type: 'payroll', source: 'payroll', lines: [{ code: '2200', debit: totalSalary }, { code: '1110', credit: totalSalary }] });
  }

  // ═══ Vendor bills + partial payments (AP lifecycle, Part 14-A) ═══
  // Field shape matches buildAndPostVendorBill() exactly (server.js) — the
  // real writer of this entity — so GET /api/ap-aging and GET /api/vendors/
  // :id/statement (both of which filter on outstandingAmount/grossAmount/
  // status, not amount/paidAmount) correctly surface these rows. JE
  // source/sourceId match the bill's own id, the same linkage the vendor-
  // statement hotfix relies on to avoid double-counting.
  const vendorBills = [];
  const billVendor = vendors[1]; // مختبر الخليج — recurring lab work bills
  for (let m = 4; m >= 0; m--) {
    const billDate = daysAgo(m * 30 + 10);
    const amt = round3(140 + rng() * 90);
    const billId = 'demo-bill-' + m;
    const paidAmount = m === 0 ? 0 : amt;
    const outstandingAmount = round3(amt - paidAmount);
    const payments = [];
    const billJe = postJE({ date: billDate, desc: `فاتورة مورد — ${billVendor.name}`, ref: 'BILL-' + billId, type: 'vendor-bill', source: 'vendor-bill', sourceId: billId, lines: [{ code: '5210', debit: amt }, { code: billVendor.accountId, credit: amt }] });
    if (m > 0) {
      const payDate = daysAgo(m * 30 + 2);
      const payJe = postJE({ date: payDate, desc: `سداد فاتورة مورد — ${billVendor.name} (قسط 1)`, ref: 'BILLPAY-' + billId + '-1', type: 'vendor-bill-payment', source: 'vendor-bill', sourceId: billId, lines: [{ code: billVendor.accountId, debit: amt }, { code: '1110', credit: amt }] });
      payments.push({ id: 'PMT-' + payJe.id, amount: amt, date: payDate, account: '1110', accountName: 'البنك — الحساب الجاري', checkNo: '', clientRef: null, jeId: payJe.id, reversed: false });
    }
    vendorBills.push({
      id: billId, number: 'BILL-' + (1000 + (5 - m)), vendorId: billVendor.id, vendorName: billVendor.name,
      billNumber: 'INV-' + (2000 + (5 - m)), billDate, dueDate: daysAgo(m * 30 - 20 >= 0 ? m * 30 - 20 : 0),
      description: 'فاتورة مختبر أسنان', grossAmount: amt, paidAmount, creditedAmount: 0, outstandingAmount,
      status: outstandingAmount <= 0.001 ? 'PAID' : 'POSTED', allocations: [{ accountCode: '5210', accountId: '5210', accountName: 'مواد مختبر أسنان', amount: amt, desc: '' }],
      liabilityAccountCode: billVendor.accountId, journalId: billJe.id,
      payments, credits: [], cancellation: null, source: 'vendor-bill', sourceId: billId,
      createdAt: billDate + 'T09:00:00.000Z', updatedAt: billDate + 'T09:00:00.000Z', createdBy: 'system',
    });
  }

  // ═══ Patient receivables + collections (AR lifecycle, Part 14-B) ═══
  // Field shape matches buildAndPostPatientReceivable()/the collection route
  // exactly (server.js) — GET /api/patient-ar-aging filters on status/
  // outstandingAmount, not the simplified fields an earlier draft of this
  // seed used.
  const patientReceivables = [];
  const arPatients = patients.slice(0, 8); // 8 of 20 patients carry a receivable
  arPatients.forEach((p, i) => {
    const serviceDate = daysAgo(20 + i * 15);
    const amt = round3(35 + rng() * 90);
    const collectedAmount = i < 5 ? amt : round3(amt * 0.4); // first 5 fully collected, rest partially outstanding
    const outstandingAmount = round3(amt - collectedAmount);
    const recId = 'demo-patrec-' + (i + 1);
    const collections = [];
    const recJe = postJE({ date: serviceDate, desc: `إيراد آجل — ${p.name}`, ref: 'PATREC-JE-' + recId, type: 'patient-receivable', source: 'patient-receivable', sourceId: recId, lines: [{ code: '1200', debit: amt }, { code: '4200', credit: amt }] });
    if (collectedAmount > 0) {
      const collDate = daysAgo(15 + i * 15);
      const collJe = postJE({ date: collDate, desc: `تحصيل من مريض — ${p.name} (قسط 1)`, ref: 'PATCOLL-' + recId + '-1', type: 'patient-receivable-collection', source: 'patient-receivable', sourceId: recId, lines: [{ code: '1100', debit: collectedAmount }, { code: '1200', credit: collectedAmount }] });
      collections.push({ id: 'COLL-' + collJe.id, amount: collectedAmount, date: collDate, account: '1100', accountName: 'الصندوق — نقدي', checkNo: '', clientRef: null, jeId: collJe.id, reversed: false });
    }
    patientReceivables.push({
      id: recId, number: 'AR-' + (1000 + i), patientId: p.id, patientName: p.name, reference: '',
      serviceDate, dueDate: daysAgo(20 + i * 15 - 30 >= 0 ? 20 + i * 15 - 30 : 0), doctorId: doctors[i % doctors.length].id,
      description: 'علاج أسنان', revenueAccountCode: '4200', receivableAccountCode: '1200',
      grossAmount: amt, collectedAmount, creditedAmount: 0, writtenOffAmount: 0, outstandingAmount,
      status: outstandingAmount <= 0.001 ? 'COLLECTED' : 'PARTIALLY_COLLECTED', recognitionJournalId: recJe.id,
      collections, credits: [], writeOff: null, cancellation: null,
      source: 'patient-receivable', sourceId: recId,
      createdAt: serviceDate + 'T09:00:00.000Z', updatedAt: serviceDate + 'T09:00:00.000Z', createdBy: 'system',
    });
  });

  // ═══ Insurance claims ═══
  const insuranceClaims = [
    { id: 'demo-claim-1', company: insuranceCompanies[0], patientId: patients[8].id, patientName: patients[8].name, date: daysAgo(45), amount: 180, status: 'approved' },
    { id: 'demo-claim-2', company: insuranceCompanies[1], patientId: patients[9].id, patientName: patients[9].name, date: daysAgo(30), amount: 220, status: 'submitted' },
    { id: 'demo-claim-3', company: insuranceCompanies[0], patientId: patients[10].id, patientName: patients[10].name, date: daysAgo(12), amount: 95, status: 'submitted' },
  ];

  // ═══ Depreciation (straight-line, months elapsed since purchase) ═══
  const depDate = daysAgo(1);
  let totalDep = 0;
  const depByAccount = {};
  fixedAssets.forEach(a => {
    const monthsElapsed = Math.floor((asOf - new Date(a.purchaseDate)) / (30 * dayMs));
    const monthlyDep = round3(a.cost / a.usefulLife / 12);
    const accumDep = round3(Math.min(a.cost, monthlyDep * monthsElapsed));
    a.accumulatedDep = accumDep;
    totalDep = round3(totalDep + accumDep);
    depByAccount[a.depExpAccount] = round3((depByAccount[a.depExpAccount] || 0) + accumDep);
  });
  postJE({
    date: depDate, desc: 'إهلاك الأصول الثابتة — تراكمي حتى ' + depDate, ref: 'DEP-CUMULATIVE', type: 'depreciation', source: 'depreciation',
    lines: [{ code: '5800', debit: totalDep }, { code: '1590', credit: totalDep }],
  });

  // ═══ Independently-computed controls (never derived from the app itself) ═══
  let grandDebit = 0, grandCredit = 0;
  journalEntries.forEach(e => e.lines.forEach(l => { grandDebit = round3(grandDebit + l.debit); grandCredit = round3(grandCredit + l.credit); }));
  const independentControls = {
    journalEntryCount: journalEntries.length,
    grandDebit, grandCredit, balanced: Math.abs(grandDebit - grandCredit) < 0.001,
    vendorOpeningBalancesSum: vendorOpenings,
    patientReceivablesOutstandingSum: round3(patientReceivables.reduce((s, r) => s + r.outstandingAmount, 0)),
    fixedAssetsCostSum: assetCost,
    fixedAssetsAccumDepSum: totalDep,
  };

  const users = [{
    id: 'demo-user-1', username: DEMO_USERNAME, passwordHash: bcrypt.hashSync(DEMO_PASSWORD, 10),
    role: 'demo', fullName: 'زائر تجريبي',
    email: 'demo@example-demo.test', tenantId: 'default', active: true,
    createdAt: openDate + 'T08:00:00.000Z',
  }];

  const companyInfo = {
    name: 'مركز اللؤلؤة لطب الأسنان', nameEn: 'Pearl Dental Center',
    phone: '+965 22XXXXXX', email: 'info@pearl-demo.test', currency: 'KWD',
  };

  const db = {
    chartOfAccounts: coa, journalEntries, auditLog,
    doctors, employees, vendors, patients, fixedAssets,
    dailyData, expenses, payroll, vendorBills, patientReceivables, insuranceClaims,
    companyInfo, users, roles: { admin: { ...DEFAULT_ROLES.admin, id: 'admin' }, demo: { ...DEFAULT_ROLES.demo, id: 'demo' } },
    doctorExpenses: [], doctorPayments: [], commissionHistory: [], uploadedFiles: [],
    invItems: [], invCategories: [], invMovements: [], recurringExpenses: [],
    scheduleConfig: {}, vouchers: [], cashReconciliation: [], accruedExpenses: [],
    budget: {}, journalMappings: [],
  };

  return { db, independentControls, seedGeneratedAt: asOfISO };
}

module.exports = { buildDemoDatabase, DEMO_USERNAME, DEMO_PASSWORD, DEMO_BRAND_NAME };
